// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Sthapna",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "sthapna.ai",
            targets: ["AppModule"],
            // Bundle identifier is intentionally kept on the legacy value so
            // existing installs keep their Keychain JWT + UserDefaults state.
            // Renaming it would log every existing user out on next deploy.
            bundleIdentifier: "com.grayman.app",
            teamIdentifier: "HHZ5J8ZBRX",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            capabilities: [
                .camera(purposeString: "sthapna.ai needs the camera to record your work intro reel."),
                .microphone(purposeString: "sthapna.ai needs the microphone to capture audio for your reel."),
                .speechRecognition(purposeString: "sthapna.ai uses speech recognition to transcribe your interview answers."),
                .locationWhenInUse(purposeString: "sthapna.ai uses your approximate location to show nearby workers and your neighbourhood on the profile.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)