// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "GrayMan",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "GrayMan",
            targets: ["AppModule"],
            bundleIdentifier: "com.grayman.app",
            teamIdentifier: "HHZ5J8ZBRX",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            capabilities: [
                .camera(purposeString: "GrayMan needs the camera to record your work intro reel."),
                .microphone(purposeString: "GrayMan needs the microphone to capture audio for your reel."),
                .speechRecognition(purposeString: "GrayMan uses speech recognition to transcribe your interview answers.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)