export const WorkerSamples = [
  {
    id: '1',
    name: 'Ramesh Kumar',
    trade: 'Electrician · 8 yrs exp',
    location: 'Andheri · Mumbai',
    rating: '4.9',
    jobs: 48,
    vouchScore: 87,
    vouched: 87,
    tags: ['Wiring', 'Installation', 'Repair', 'Maintenance', 'Circuit', 'Equipment'],
    verifiedTagIndices: new Set([0, 1]),
    gradientEndHex: '#ee6c4d',
    initials: 'RK',
    distance: '1.2',
  },
  {
    id: '2',
    name: 'Suresh Patel',
    trade: 'Plumber · 5 yrs exp',
    location: 'Bandra · Mumbai',
    rating: '4.7',
    jobs: 32,
    vouchScore: 72,
    vouched: 72,
    tags: ['Pipe Fitting', 'Drainage', 'Leaks', 'Bathroom', 'Kitchen'],
    verifiedTagIndices: new Set([0, 2]),
    gradientEndHex: '#118AB2',
    initials: 'SP',
    distance: '2.4',
  },
  {
    id: '3',
    name: 'Priya Sharma',
    trade: 'Nurse · 6 yrs exp',
    location: 'Dadar · Mumbai',
    rating: '5.0',
    jobs: 64,
    vouchScore: 94,
    vouched: 94,
    tags: ['Patient Care', 'IV Therapy', 'Wound Care', 'Elderly', 'Home Visit'],
    verifiedTagIndices: new Set([0, 1, 2]),
    gradientEndHex: '#C9184A',
    initials: 'PS',
    distance: '0.8',
  },
  {
    id: '4',
    name: 'Mohan Das',
    trade: 'Carpenter · 12 yrs exp',
    location: 'Kurla · Mumbai',
    rating: '4.8',
    jobs: 91,
    vouchScore: 81,
    vouched: 81,
    tags: ['Furniture', 'Cabinets', 'Doors', 'Flooring', 'Polishing'],
    verifiedTagIndices: new Set([0, 1]),
    gradientEndHex: '#C1440E',
    initials: 'MD',
    distance: '3.1',
  },
  {
    id: '5',
    name: 'Kavita Reddy',
    trade: 'Painter · 4 yrs exp',
    location: 'Powai · Mumbai',
    rating: '4.6',
    jobs: 27,
    vouchScore: 65,
    vouched: 65,
    tags: ['Interior', 'Exterior', 'Texture', 'Waterproofing'],
    verifiedTagIndices: new Set([0]),
    gradientEndHex: '#7B2D8B',
    initials: 'KR',
    distance: '1.9',
  },
];

export const AllCategories = [
  'All', 'Electrician', 'Plumber', 'Nurse', 'Carpenter', 'Painter',
  'Mechanic', 'Welder', 'Mason', 'AC Repair', 'Driver', 'Cook',
  'Security Guard', 'Sales Executive', 'Receptionist', 'Data Entry',
  'JCB Operator', 'Housekeeping',
];
